services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: cardapio_digital_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5436:5432'
    volumes:
      - pgdata2:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6381:6379'

volumes:
  pgdata2:
