export class AdminDashboardRevenueByHourResponseDto {
  public constructor(
    /** Hour of day in local time. */
    public readonly hour: number,
    /** Paid revenue for this hour. */
    public readonly revenue: number,
    /** Paid order count for this hour. */
    public readonly orders: number,
  ) {}
}

export class AdminDashboardTopProductResponseDto {
  public constructor(
    /** Product display name. */
    public readonly name: string,
    /** Quantity sold today. */
    public readonly qty: number,
    /** Revenue generated by this product today. */
    public readonly revenue: number,
  ) {}
}

export class AdminDashboardWeeklyRevenueResponseDto {
  public constructor(
    /** Date label for the revenue bucket. */
    public readonly date: string,
    /** Paid revenue for this day. */
    public readonly revenue: number,
    /** Paid order count for this day. */
    public readonly orders: number,
  ) {}
}

export class AdminDashboardResponseDto {
  public constructor(
    /** Number of orders created today. */
    public readonly todayOrdersCount: number,
    /** Number of paid-status orders created today. */
    public readonly todayPaidCount: number,
    /** Paid revenue for today. */
    public readonly todayRevenue: number,
    /** Average paid ticket for today. */
    public readonly avgTicket: number,
    /** Today's order counts grouped by status. */
    public readonly ordersByStatus: Record<string, number>,
    /** Today's paid revenue grouped by hour. */
    public readonly revenueByHour: AdminDashboardRevenueByHourResponseDto[],
    /** Top products sold today. */
    public readonly topProducts: AdminDashboardTopProductResponseDto[],
    /** Today's paid order counts grouped by payment method. */
    public readonly byPayment: Record<string, number>,
    /** Paid revenue for the last seven days. */
    public readonly weeklyRevenue: AdminDashboardWeeklyRevenueResponseDto[],
  ) {}
}
